codeql:
  db_directory: /home/poorna/capstone/rag-refactor/ragRefactor/sample_dbs/code_ql/
  repo_directory: /home/poorna/capstone/rag-refactor/ragRefactor/sample_dbs/code_ql/
  sample_db:
    pet_clinic: spring-petclinic-db
  sample_codebase:
    pet_clinic: spring-petclinic
  currect_db: spring-petclinic-db
  queries_path: /home/poorna/capstone/rag-refactor/ragRefactor/dataService/code_ql/queries/

files_path: /home/poorna/capstone/rag-refactor/ragRefactor/sample_dbs/files
